version: '3.8'

services:
  sabanas_api:
    image: sabanas:1.0
    build: 
      context: ./
      dockerfile: dockerfile
    container_name: SABANAS-API
    ports:
      - "8001:8001"
    env_file:
      -  app/.env
    networks:
      - sabanas_net
    
networks:
  sabanas_net:
    driver: bridge